# Bloque del servicio
apiVersion: v1
kind: Service

metadata:
  name: svc-app-ejemplo
  labels: 
    app: app-ejemplo

# tipo de servicio LoladBalancer
spec:
  type: LoadBalancer
  selector:
    proyecto: app-nginx

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

# version y tipo de archivo
apiVersion: apps/v1
kind: Deployment

# metadadata y etiquetas.
metadata:
  name: ejm-deployment
  labels:
    app: app-ejemplo

# especificaciones del deployment
spec:
  selector:
    matchLabels:
      proyecto: app-nginx
  replicas: 1

  template:
    metadata:
      name: nginx/latest
      labels:
        proyecto: app-nginx

# contenedores.
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
