apiVersion: v1
kind: Service

metadata:
  name: svc-app-ejemplo
  labels: 
    app: app-ejemplo
//Este es un comentario
spec:
  type: LoadBalancer
  selector:
    proyecto: app-nginx
//Comentario Ricardo Castro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---


apiVersion: apps/v1
kind: Deployment

# metadadata y etiquetas.
metadata:
  name: ejm-deployment
  labels:
    app: app-ejemplo

# especificaciones del deployment
spec:
  selector:
    matchLabels:
      proyecto: app-nginx
  replicas: 1

  template:
    metadata:
      name: nginx
      labels:
        proyecto: app-nginx

# contenedores.
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
# ------------- comment by mateo rosas
          volumeMounts:
            - name: persistent-storage-nginx
              mountPath: /usr/share/nginx/html

      volumes:
        - name: persistent-storage-nginx
          persistentVolumeClaim:
            claimName: pvc-nginx
